open-source-uom/myuom

- README.md
> Add Contributors list

- README.md
> Links to github instead gitlab

- package-lock.json
- package.json
- prettier.config.js
- src/components/MenuBox.jsx
- src/components/maps/MapCords.jsx
- src/components/restaurant/RestaurantMenu.jsx
- src/pages/FirstYearInfoPage.jsx
- src/pages/MapPage.jsx
- enforces ternary operator `(condition ? <Comp /> : null)` instead of short-circuit `(condition && <Comp />)` to avoid unintentionally rendered `0`s 
- adds `prettier` config file & dev dependancy
> fix(conditionalRendering): ternary instead of &&

- src/pages/AboutSettingsPage.jsx
> Update about section copyright year

- src/App.js
- src/assets/locales/el/error404.js
- src/assets/locales/en/error404.js
- src/i18n.js
- src/pages/Error404.jsx
Fixes #64 
As an errorPage404 is important element for a website (discussed in #64)
Changes Done:-
1) Added an extra Route path `/*` and displaying <Error404 /> page.
2) Developed and designed <Error404 /> so that the user don't get an empty page on an incorrect route.
> added error404 page on incorrect routes

- .prettierignore
> Avoid reformat files

- src/assets/data/ScheduleLink.js
fixes #72  
- Fixed a typo in the Department Code for Educational & Social Policy Department.
- Updated the Course Schedule and Exam Schedule URLs for the department Business Administration.
> Fixed bug in Course Schedules Page

- src/components/ServicesCard.jsx
Fixes #62 
Changes done in ServicesCard  - 
1. Applied flex properties to Link component
2. Changed width of the Flex Component 
Made ui consistent
> Changed the content width on Services Page

- package-lock.json
- package.json
You have to require atleast node 14.21.x or higher version of node to develop this project
fixes: #43
> Set node.js version for development

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Include bug and feature issue template

- src/components/professors/ProfCard.jsx
fixes #68 
Changes done:
Add t() function to prof.title
> 68 professor title

- src/components/MenuBox.jsx
> fix(home): rerender disabled cards on department pick

- .gitattributes
> Enforce normalization of line ending to LF, fixes #21

- Dockerfile
> Use a specific node base image tag instead lts-slim

- src/pages/AboutSettingsPage.jsx
please, Look at the issue for more info.
fixes: #60
> Improve AboutSettingsPage component

- .github/workflows/build.yml
We don't need to run CI when we have changed not related
> Excluding some  paths in CI

- src/assets/ConfigRoutes.js
- src/assets/data/Graduation.js
- src/assets/data/Services.js
- src/assets/data/announcements.js
- src/components/MenuBox.jsx
- src/components/ServicesCard.jsx
- src/pages/AnnouncementPage.jsx
- src/pages/LibraryPage.jsx
- src/pages/MapPage.jsx
Fixes #80 
For each external link where an English version of the site was both **available** and **up-to-date** (in many cases, although an English version existed, the content was last updated in 2023 or 2022), an appropriate redirection was included.
Also fixed some wrong redirection links.
> Added English Language Redirection

- src/assets/locales/el/about_page.js
- src/assets/locales/en/about_page.js
- src/components/ContributorsCard.jsx
- src/pages/AboutSettingsPage.jsx
> Add contributors section

- .github/workflows/build.yml
- .prettierignore
- package.json
making sure prettier work locally and integrate with node.js CI
fixes: #134
> Fix: prettier work locally and integrate with node.js CI

- package.json
[npm pkg fix](https://docs.npmjs.com/cli/v9/commands/npm-pkg) should fix your package.json issues automatically.
> Include git information in package.json  

- .github/workflows/build.yml
- .prettierignore
- package.json
Reverts open-source-uom/myuom#146
fixes: #160
> Revert "Fix: prettier work locally and integrate with node.js CI"

- .github/workflows/deploy-prod.yml
- src/pages/AboutSettingsPage.jsx
Now whenever something new is commited/ merged to main it will be automatically upload to the production server
> Add an Action to deploy to production

- .github/dependabot.yaml
> keep property `"ignore"` inside the schema

- .github/PULL_REQUEST_TEMPLATE.md
- Added the PR template in `.github/`
> [Feat] PR Template added

- src/components/restaurant/TodaysRestaurantMenu.jsx
link to issue is #317 
It solves the issue
> added arrows to swip

- src/assets/locales/el/restaurant.js
- src/assets/locales/en/restaurant.js
- src/components/restaurant/Schedule.jsx
UI responsiveness fixes — holiday break mode only
Grammar improvements in holiday break translations -i18n-
> Slight changes to the holiday break feature in the restaurant schedule

- src/assets/data/Services.js
- src/assets/locales/el/services.js
- src/assets/locales/en/services.js
Replace broken external service links with fallback URLs to uom.gr/
> Fix broken link and icons on /services 

- package-lock.json
- package.json
- src/App.jsx
- src/components/Header.jsx
- src/components/MenuBox.jsx
- src/components/settings/SettingsDrawer.jsx
- src/index.jsx
- src/pages/AnnouncementPage.jsx
- src/pages/Error404.jsx
- src/pages/GraduationPage.jsx
- src/pages/SchedulePage.jsx
use latest `react-router` instead `react-router-dom`. I have tested everything working fine.
closes: #343
> chore: use latest react-router

- src/components/restaurant/MenuTable.jsx
Add i18n support to MenuTable.jsx to keep both languages
> Fix to support both languages
